name: Ruby Gem

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Run tests
      run: bundle exec rake spec

    - name: Run RuboCop
      run: bundle exec rake rubocop

    - name: Publish to RubyGems
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
      run: |
        mkdir -p ~/.gem
        echo "---\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials
        chmod 0600 ~/.gem/credentials
        gem build *.gemspec
        gem push *.gem
